print("Hello world")
import sqlite3
conn = sqlite3.connect('NBA_Stats.db')
print("Opened/created database successfully")

conn.execute("""CREATE TABLE TeamTotals
            (Abbr TEXT PRIMARY KEY,
             TeamName VARCHAR(255),
             GamesPlayed INTEGER,
             Minutes INTEGER,
             FGM INTEGER,
             FGA INTEGER,
             FG_Perc REAL,
             ThreePointM INTEGER,
             ThreePointA INTEGER,
             ThreePoint_Perc REAL,
             TwoPointM INTEGER,
             TwoPointA INTEGER,
             TwoPoint_Perc REAL,
             FT INTEGER,
             FTA INTEGER,
             FT_Perc REAL,
             ORB INTEGER,
             DRB INTEGER,
             TRB INTEGER,
             AST INTEGER,
             STL INTEGER,
             BLK INTEGER,
             TOV INTEGER,
             PF INTEGER,
             PTS INTEGER);""")
print("Table TeamTotals created")

conn.execute("""CREATE TABLE TeamOppTotals
            (Abbr TEXT PRIMARY KEY,
             TeamName VARCHAR(255),
             GamesPlayed INTEGER,
             Minutes INTEGER,
             FGM INTEGER,
             FGA INTEGER,
             FG_Perc REAL,
             ThreePointM INTEGER,
             ThreePointA INTEGER,
             ThreePoint_Perc REAL,
             TwoPointM INTEGER,
             TwoPointA INTEGER,
             TwoPoint_Perc REAL,
             FT INTEGER,
             FTA INTEGER,
             FT_Perc REAL,
             ORB INTEGER,
             DRB INTEGER,
             TRB INTEGER,
             AST INTEGER,
             STL INTEGER,
             BLK INTEGER,
             TOV INTEGER,
             PF INTEGER,
             PTS INTEGER);""")
print("Table TeamOppTotals created")

conn.execute("""CREATE TABLE PlayerTotals
            (ID PRIMARY KEY,
             PlayerName VARCHAR(255),
             Pos TEXT,
             Age Integer,
             Team TEXT,
             G INTEGER,
             GS INTEGER,
             MP INTEGER,
             FGM INTEGER,
             FGA INTEGER,
             FG_Perc REAL,
             ThreePointM INTEGER,
             ThreePointA INTEGER,
             ThreePoint_Perc REAL,
             TwoPointM INTEGER,
             TwoPointA INTEGER,
             TwoPoint_Perc REAL,
             eFG_Perc Real,
             FT INTEGER,
             FTA INTEGER,
             FT_Perc REAL,
             ORB INTEGER,
             DRB INTEGER,
             TRB INTEGER,
             AST INTEGER,
             STL INTEGER,
             BLK INTEGER,
             TOV INTEGER,
             PF INTEGER,
             PTS INTEGER);""")
print("Table PlayerTotals created")

